name: Account
on:
  workflow_dispatch:
    inputs:
      level:
        description: Logging Level
        required: true
        default: INFO
        type: choice
        options:
          - CRITICAL
          - FATAL
          - ERROR
          - WARNING
          - WARN
          - INFO
          - DEBUG
          - NOTSET
      pool:
        description: Number of threads
        required: true
        default: 16
      retry:
        description: Number of retries
        required: true
        default: 3
    branches:
      - main
  schedule:
    - cron: '0 0 */3 * *'
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  account:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          git config --local user.name AutoUpdate[bot]
          git config --local user.email AutoUpdate[bot]@users.noreply.github.com
      - name: Run 70game.py
        run: python 70game.py
      - name: Run push.py
        if: steps.run_70game.outcome == 'success'
        run: python push.py
